---
deployment:
  tasks:
    - export DEPLOYPATH=/home/swki8708/wive-app.fr/
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp *.html $DEPLOYPATH
    - /bin/cp -R assets/css $DEPLOYPATH
    - /bin/cp -R assets/images $DEPLOYPATHs